apiVersion: apps/v1
kind: Deployment
metadata:
  name: frg-fe
  namespace: frg-develop-fe
  labels:
    app: frg-fe
spec:
  selector:
    matchLabels:
      app: frg-fe
      role: fe
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: frg-fe
        role: fe
    spec:
      containers:
      - name: frg-fe
        image: '${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_SLUG}:${CI_PIPELINE_ID}'
        resources:
          limits:
            memory: 128Mi
            cpu: 1
          requests:
            memory: 64Mi
            cpu: 128m
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      imagePullSecrets:
        - name: gitlab-registry
