apiVersion: v1
kind: Service
metadata:
  name: frg-fe-clusterip
  namespace: frg-develop-fe
  labels:
    app: frg-fe
    role: fe
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    name: http
    protocol: TCP
  selector:
    app: frg-fe
    role: fe